# Generated by Django 2.1.15 on 2020-08-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=500)),
                ('actor_img', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama_name', models.CharField(max_length=500)),
                ('drama_img', models.CharField(max_length=500)),
                ('drama_kind', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500)),
                ('group_img', models.CharField(max_length=500)),
                ('spot_cd', models.ManyToManyField(null=True, related_name='spot_group', to='maps.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=500)),
                ('show_img', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Showman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showman_name', models.CharField(max_length=500)),
                ('showman_img', models.CharField(max_length=500)),
                ('show_cd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Show')),
                ('spot_cd', models.ManyToManyField(null=True, related_name='spot_show', to='maps.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=500)),
                ('singer_img', models.CharField(max_length=500)),
                ('group_cd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('spot_cd', models.ManyToManyField(null=True, related_name='spot_singer', to='maps.Spot')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='drama_cd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Drama'),
        ),
        migrations.AddField(
            model_name='actor',
            name='spot_cd',
            field=models.ManyToManyField(null=True, related_name='spot_actor', to='maps.Spot'),
        ),
    ]
