# Generated by Django 2.1.15 on 2020-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_A',
            new_name='answer_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_B',
            new_name='answer_b',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='chioce',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.CharField(default='okij', max_length=100),
            preserve_default=False,
        ),
    ]
